services:
  auth-service:
    image: ghcr.io/prismedroiteext/bzhspauth
    ports:
      - "8082:8082"
    environment:
      - AUTH_DB_HOST=${AUTH_DB_HOST}
      - AUTH_DB_USER=${AUTH_DB_USER}
      - AUTH_DB_PASSWORD=${AUTH_DB_PASSWORD}
      - AUTH_DB_NAME=${AUTH_DB_NAME}
      - DB_PORT=${DB_AUTH_PORT}
      - DB_SSLMODE=${DB_SSLMODE}
      - DB_TIMEZONE=${TIMEZONE}
      - GIN_MODE=${GIN_MODE}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db-auth
  db-auth:
    image: postgres:17
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"


  product-service:
    image: ghcr.io/prismedroiteext/bzhspproduct
    ports:
      - "8081:8081"
    environment:
      - PRODUCT_DB_HOST=${PRODUCT_DB_HOST}
      - PRODUCT_DB_USER=${PRODUCT_DB_USER}
      - PRODUCT_DB_PASSWORD=${PRODUCT_DB_PASSWORD}
      - PRODUCT_DB_NAME=${PRODUCT_DB_NAME}
      - DB_PORT=${DB_PRODUCT_PORT}
      - DB_SSLMODE=${DB_SSLMODE}
      - DB_TIMEZONE=${TIMEZONE}
      - GIN_MODE=${GIN_MODE}
    depends_on:
      - db-product
  db-product:
    image: postgres:17
    environment:
      POSTGRES_USER: ${PRODUCT_DB_USER}
      POSTGRES_PASSWORD: ${PRODUCT_DB_PASSWORD}
      POSTGRES_DB: ${PRODUCT_DB_NAME}
    volumes:
      - product-db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
  
  front-service:
    image: ghcr.io/prismedroiteext/bzhspfront
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - AUTH_API_URL=${AUTH_API_URL}
      - PRODUCT_API_URL=${PRODUCT_API_URL}


volumes:
  auth-db-data:
    driver: local
    mountpoint: ./volumes/auth-db-data
  product-db-data:
    driver: local
    mountpoint: ./volumes/product-db-data

